gui:
    nerdFontsVersion: '3'
git:
    mainBranches: [master, main, dev]
    skipHookPrefix: WIP
    paging:
        colorArg: always
        useConfig: true
services:
    'github.eng.tenable.com': 'github:github.eng.tenable.com'
